name: stt_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^8.0.0+6
  path_provider: ^2.0.1
  permission_handler: ^6.1.0
  grpc: ^3.0.0
  protobuf: ^2.0.0
  async: ^2.2.0
  sqflite: ^2.0.0+2
  path: ^1.8.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
